[package]
name = "rust_native"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { version = "0.5.2", features = ["api-4-7", "experimental-threads"] }
lib3mf-core = { version = "0.4", features = ["parallel"] }
# Dependency of lib3mf-core that wasn't re-exported.
glam = "0.31.1"
camino = "1.2.2"
crossbeam = "0.8.4"
rust-ini = "0.21.3"
